### ISSUE TITLE
lupo has no go export

### ISSUE THREAD

**Issue by iamveene** [vithakur/lupo#3]
Hi, when I try to run !lupo.go I get the message "lupo has no go export".
Anything I might have missed?

"""
0:000> .chain
Extension DLL search Path:
    C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\WINXP;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\winext;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\winext\arcade;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\pri;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64;C:\Users\vinicios\AppData\Local\Dbg\EngineExtensions;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\Users\vinicios\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\vinicios\AppData\Local\Programs\Python\Python38-32\;C:\Users\vinicios\AppData\Local\Microsoft\WindowsApps;C:\Users\vinicios\AppData\Roaming\Python\Python38\Scripts\;C:\Users\vinicios\.local\bin\;C:\Program Files (x86)\Nmap;C:\Users\vinicios\go\bin
Extension DLL chain:
    lupo: API 1.0.0, built Wed May 11 02:53:23 2022
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\winext\lupo.dll]
    dbghelp: image 10.0.22000.194, API 10.0.6, 
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll]
    ext: image 10.0.22000.194, API 1.0.0, 
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\winext\ext.dll]
    exts: image 10.0.22000.194, API 1.0.0, 
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\WINXP\exts.dll]
    uext: image 10.0.22000.194, API 1.0.0, 
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\winext\uext.dll]
    ntsdexts: image 10.0.22000.194, API 1.0.0, 
        [path: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\WINXP\ntsdexts.dll]
0:000> .extmatch /D /e lupo *
!lupo.c
!lupo.gall
!lupo.gcopy
!lupo.gcreate
!lupo.gnet
!lupo.gpcreate
!lupo.guri
0:000> !lupo.go
lupo has no go export
"""

**Comment by malienist** [comment]
Hi, 
The go export has been deprecated, documentation for the latest release is here: https://github.com/malienist/lupo/wiki/Lupo-Wiki
