### ISSUE TITLE
The call to LoadLibrary(XTR.dll) failed, Win32 error 0n126 "The specified module could not be found." Please check your debugger configuration and/or network access.

### ISSUE THREAD

**Issue by neofallxyz** [vithakur/lupo#4]
I am already following instructions for installation but when I run the lupo plugin,  Windbg can't find XTR.dll : 

![tempsnip](https://user-images.githubusercontent.com/22272022/176153107-7b55b6dc-ab39-4518-9309-de9b820dd00d.png)

XTR.dll already in path winext :
![tempsnip](https://user-images.githubusercontent.com/22272022/176153481-7794657a-f092-482e-962c-194b95748a9e.png)

Visual C++ I Have: 
![tempsnip](https://user-images.githubusercontent.com/22272022/176153761-0d612660-22ea-4d8b-911f-f1f84f1a3661.png)

How to fix this?

**Comment by malienist** [comment]
ACK

**Comment by malienist** [comment]
What version of WinDbg are you using? 32 or 64?

**Comment by malienist** [comment]
I think you might be using the 32-bit version of WinDBG but have all the files in the 64-bit path.. let me know once you have checked and confirmed.

**Comment by neofallxyz** [comment]
> What version of WinDbg are you using? 32 or 64?

I'm using 64 bit, I already solved this issue with installing all Visual C++ library (old one installed too) https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170.

**Comment by malienist** [comment]
Perfect!
